<strong>Підготовка датасетів</strong>

In [1]:
#імпорт бібліотек
import pandas as pd

In [ ]:
url_survey_results_public = "https://drive.google.com/file/d/1H8jcIjt_rjXXKWvS-uUNGFJu6hw53eUQ/view?usp=drive_link"
url_survey_results_schema = "https://drive.google.com/file/d/1DNlDPTwMQ-Og_zH1IMNCuDTOwh_QBGge/view?usp=drive_link"

In [2]:
#читання CSV-файлів з використанням стандартного кодування UTF-8
df_raw = pd.read_csv(url_survey_results_public)
df_schema = pd.read_csv(url_survey_results_schema)

C:\Users\myaro\AppData\Local\Temp\ipykernel_11388\2112719184.py:2: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv("C:/Users/myaro/Desktop/Data analytics/Block 2 Final/src/survey_results_public.csv")

In [3]:
#відображення всіх колонок датасету
pd.set_option('display.max_columns', None)

In [4]:
#відображення датасету з відповідями
df_raw.head(5)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [5]:
#відображення датасету із структурою опитування
df_schema.head(5)

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

<strong>Завдання 1.</strong> Підрахунок загальної кількості респондентів

За допомогою метода .nunique() рахуємо кількість унікальних значень ResponseID

In [6]:
df_raw['ResponseId'].nunique()

49191

<strong>Завдання 2.</strong> Аналіз повноти відповідей респондентів

Отримуємо список запитань із датасету survey_results_schema за допомогою методів set(), .unique()

In [7]:
#формуємо список запитань
questions_list = set(df_schema['qname'].unique())
questions_list

{'AIAcc',
 'AIAgentChallenges',
 'AIAgentChange',
 'AIAgentExtWrite',
 'AIAgentExternal',
 'AIAgentImpact',
 'AIAgentKnowWrite',
 'AIAgentKnowledge',
 'AIAgentObsWrite',
 'AIAgentObserveSecure',
 'AIAgentOrchWrite',
 'AIAgentOrchestration',
 'AIAgent_Uses',
 'AIAgents',
 'AIComplex',
 'AIExplain',
 'AIFrustration',
 'AIHuman',
 'AILearnHow',
 'AIModels',
 'AIModelsChoice',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'AIOpen',
 'AISelect',
 'AISent',
 'AIThreat',
 'AITool',
 'Age',
 'AgentUsesGeneral',
 'CommPlatform',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'CompTotal',
 'Country',
 'Currency',
 'Database',
 'DatabaseChoice',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'DevEnvs',
 'DevEnvsChoice',
 'DevType',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'ICorPM',
 'Industry',
 'JobSat',
 'JobSatPoints_1',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_15_TEXT',
 'JobSatPoints_16',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'Language',
 'LanguageChoice',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'LearnCode',
 'LearnCodeAI',
 'LearnCodeChoose',
 'MainBranch',
 'NewRole',
 'OfficeStackAsync',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'OpSys',
 'OrgSize',
 'Platform',
 'PlatformChoice',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'PurchaseInfluence',
 'RemoteWork',
 'SOAccount',
 'SOComm',
 'SODuration',
 'SOFriction',
 'SOPartFreq',
 'SOTags',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'SOVisitFreq',
 'SO_Actions_1',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_7',
 'SO_Actions_9',
 'SO_Dev_Content',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechOppose_1',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'TechOppose_16',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'ToolCountPersonal',
 'ToolCountWork',
 'Webframe',
 'WebframeChoice',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'WorkExp',
 'YearsCode'}

Формуємо список спільних колонок за допомогою перетину множин:

In [8]:
common_list = df_raw.columns.intersection(questions_list)
common_list

Index(['MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl',
       'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow',
       ...
       'AIAgentKnowWrite', 'AIAgentOrchestration', 'AIAgentOrchWrite',
       'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal',
       'AIAgentExtWrite', 'AIHuman', 'AIOpen', 'JobSat'],
      dtype='object', length=126)

Формуємо датафрейм, який містить лише спільні колонки:

In [67]:
df_common = df_raw[common_list]
df_common.head(5)

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveEntry,SOTagsWant Entry,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,JobSat
0,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community)","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a new career or industry,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,No,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",10.0
1,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or industry voluntarily,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year","Chat (people);Message Boards;Long-form articles;Videos;Coding challenges;Logic games/puzzles;Lists of recommendations (tools, frameworks, technologies, etc.);Direct messaging of users;Job board;Day-in-the-life profiles/interviews with experts",6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I want to compare different solutions;When I have ethical or security concerns about code,All skills. AI is a flop.,9.0
2,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-employed",None of the above,10.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Videos (not associated with specific online course or certification);Technical documentation (is generated for/by the tool or system),"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps;Technical documentation (is generated for/by the tool or system);Videos (not associated with specific online course or certification),12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or industry involuntarily,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,Solid.js,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year","Chat (people);Videos;Lists of recommendations (tools, frameworks, technologies, etc.);Chat (bot/AI)",3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,"Understand how things actually work, problem solving, and algorithms",8.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies","AI CodeGen tools or AI-enabled apps;Videos (not associated with specific online course or certification);Other online resources (e.g. standard search, forum, online community)",5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a new career or industry,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,NaN,NaN,No,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Overflow,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,"AI solutions that are almost right, but not quite;I don’t use AI tools regularly",NO,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,NaN,6.0
4,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-employed","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn new coding techniques or programming languages",NaN,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies","Technical documentation (is generated for/by the tool or system);Other online resources (e.g. standard search, forum, online community)",22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source and is currently used by more than just myself but no purchase was made",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a new career or industry,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks","AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the task correctly",7.0

Змінна full_answers повертає кількість респондентів, що відповіли на всі питання опитувальника.

In [70]:
full_answers = df_common.dropna().shape[0]
print(f"{full_answers} respondents answered all the questions in the survey.")

0 respondents answered all the questions in the survey.

В датасеті відсутні респонденти, що відповіли на всі запитання опитувальника. Це може бути пов'язано з тим, що деякі поля є необов'язковими для заповнення.

<strong>Завдання 3.</strong> Статистичний аналіз досвіду респондентів

Порахуємо кількість рядків з пропущеним WorkExp:

In [11]:
df_raw['WorkExp'].isna().sum()

np.int64(6298)

Перевіримо міри центральної тенденції датафрейму, включно з NaN-значеннями:

In [12]:
print(f'Mean: {df_raw['WorkExp'].mean().round()}')
print(f'Median: {df_raw['WorkExp'].median()}')
print(f'Mode: {df_raw['WorkExp'].mode()[0]}')

Mean: 13.0
Median: 10.0
Mode: 10.0

Із розрахунків видно, що median < mean, тому для заповнення пустих значень, без значних спотворень результатів, візьмемо медіанне значення WorkExp.

Створимо новий датафрейм та заповнимо пропущені значення:

In [13]:
df = df_raw.copy()
df['WorkExp'] = df['WorkExp'].fillna(value = df['WorkExp'].median())

Виводимо міри центральної тенденції - середнє, медіану та моду:

In [14]:
print(f'Mean: {df['WorkExp'].mean().round()}')
print(f'Median: {df['WorkExp'].median()}')
print(f'Mode: {df['WorkExp'].mode()[0]}')

Mean: 13.0
Median: 10.0
Mode: 10.0

<strong>Завдання 4.</strong> Аналіз віддаленої роботи

Щоб визначити кількість респондентів, що працюють віддалено, порахуємо кількість рядків зі значенням Remote у стовпці RemoteWork:

In [15]:
remote_count = (df['RemoteWork'] == 'Remote').sum()
remote_count

np.int64(10931)

<strong>Завдання 5.</strong> Визначення популярності Python

Створимо змінну worked_with_python, де значенню True відповідатимуть рядки, що містять слово 'Python' (за допомогою str.contains()), та False - рядки, що не містять його, або значення NaN:

In [16]:
worked_with_python = df['LanguageHaveWorkedWith'].str.contains('Python', case = False, na = False)
worked_with_python

0        False
1        False
2        False
3        False
4         True
         ...
49186    False
49187    False
49188    False
49189    False
49190    False
Name: LanguageHaveWorkedWith, Length: 49191, dtype: bool

Розраховуємо відсоток респондентів, що працюють з мовою Python:

In [17]:
worked_with_python_prct = round((worked_with_python.sum() / df['ResponseId'].nunique()) * 100, 1)
print(f"Python users: {worked_with_python_prct}%")

Python users: 37.5%

<strong>Завдання 6.</strong> Аналіз шляхів навчання програмуванню

Задамо висоту комірок залежно від вмісту:

In [18]:
pd.set_option('display.max_colwidth', None)
df.head(1)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community)","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a new career or industry,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Gradle,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search for answers,Project planning;Deployment and monitoring;Learning new concepts or technologies,Documenting code;Debugging or fixing code;Testing code;Committing and reviewing code;Predictive analytics;Generating content or synthetic data;Creating or maintaining documentation,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI agents have reduced the time spent on specific development tasks.,AI agents have helped me automate repetitive tasks.;AI agents have improved the quality of my code.;AI agents have accelerated my learning about new technologies or codebases.;AI agents have helped me solve complex problems more effectively.;AI agents have improved collaboration within my team.,NaN,NaN,NaN,I am concerned about the accuracy of the information provided by AI agents.;It takes significant time and effort to learn how to use AI agents effectively.,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security and privacy of data when using AI agents.,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0

Подібно до попереднього завдання, створимо змінну studied_courses:

In [19]:
studied_courses = df['LearnCode'].str.contains('Online Courses or Certification', case = False, na = False)
studied_courses

0         True
1         True
2         True
3        False
4        False
         ...
49186    False
49187     True
49188     True
49189    False
49190     True
Name: LearnCode, Length: 49191, dtype: bool

Виводимо кількість респондентів, що навчалися програмуванню через онлайн-курси:

In [20]:
print(f"{studied_courses.sum()} respondents learned to code with online courses.")

10973 respondents learned to code with online courses.

<strong>Завдання 7.</strong> Географічний аналіз компенсації Python-розробників

За допомогою створеної раніше маски фільтруємо респондентів, що програмують на Python:

In [21]:
df_python = df[worked_with_python]
df_python

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-employed","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn new coding techniques or programming languages",NaN,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies","Technical documentation (is generated for/by the tool or system);Other online resources (e.g. standard search, forum, online community)",22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source and is currently used by more than just myself but no purchase was made",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a new career or industry,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;PowerShell;Python;SQL;TypeScript;VBA;Visual Basic (.Net),C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracle;PostgreSQL;Redis;SQLite,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Maven (build tool);MSBuild;npm;NuGet;Pip,Amazon Web Services (AWS);APT;Docker;Maven (build tool);MSBuild;npm;NuGet;Pip,Amazon Web Services (AWS);APT;Docker;Maven (build tool);MSBuild;npm;NuGet;Pip,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/JupyterLab;Notepad++;PyCharm;Rider;Visual Studio;WebStorm,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Notepad++;PyCharm;Rider;Visual Studio;WebStorm,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Notepad++;PyCharm;Rider;Visual Studio;WebStorm,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,"Stack Overflow;Stack Exchange;GitHub (public projects, not private repos)","Stack Overflow;Stack Exchange;GitHub (public projects, not private repos)","Stack Overflow;Stack Exchange;GitHub (public projects, not private repos)",NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debugging or fixing code;Search for answers;Learning new concepts or technologies,Project planning;Documenting code;Testing code;Committing and reviewing code;Deployment and monitoring;Predictive analytics;Creating or maintaining documentation,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns about the security and privacy of data when using AI agents.,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the task correctly",60000.0,7.0
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Transitioning to retirement (gradually reducing work hours),22.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Books / Physical media;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps;Blogs or podcasts,"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps;Blogs or podcasts,30.0,"Architect, software or solutions",Less than 20 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Personal Project,12.0,2.0,1.0,10.0,4.0,5.0,8.0,6.0,7.0,14.0,NaN,14.0,3.0,4.0,9.0,1.0,5.0,2.0,11.0,12.0,15.0,NaN,Software Development,7.0,9.0,11.0,10.0,14.0,12.0,4.0,2.0,5.0,13.0,6.0,3.0,1.0,15.0,8.0,NaN,Yes,I have strongly considered changing my career and/or the industry I work in,10.0,10.0,Ukraine,USD United States dollar,72000.0,Yes,Bash/Shell (all shells);HTML/CSS;JavaScript;Python;SQL;TypeScript,Assembly;Bash/Shell (all shells);HTML/CSS;JavaScript;Python;Ruby;SQL;TypeScript,Bash/Shell (all shells);HTML/CSS;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,MongoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,PostgreSQL;SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Google Cloud;Homebrew;npm;Pip,APT;Cargo;Docker;Homebrew;Pip,APT;Docker;Homebrew;Pip,NaN,NaN,Yes,Angular;Django,Django,Django,NaN,NaN,Yes,PyCharm;Visual Studio Code;WebStorm,Claude Code;PyCharm;Visual Studio Code,PyCharm;Visual Studio Code,NaN,NaN,Amazon Bedrock,Odoo;Large Language Model;RAG,NaN,NaN,NaN,MacOS;iOS;iPadOS,MacOS;Ubuntu;Linux (non-WSL),GitHub;Jira,GitHub;GitLab;Jira;Wikis,GitHub;Jira,NaN,NaN,"Stack Overflow;Stack Exchange;GitHub (public projects, not private repos);X;YouTube;LinkedIn;Substack","Stack Overflow;Stack Exchange;Reddit;GitHub (public projects, not private repos);X;YouTube;LinkedIn","Stack Overflow;Stack Exchange;GitHub (public projects, not private repos);X;YouTube;LinkedIn",NaN,NaN,Yes,openAI GPT (chatbot models),Anthropic: Claude Sonnet;openAI GPT (chatbot models);openAI Reasoning models;Perplexity Sonar models,openAI GPT (chatbot models),NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year","Chat (people);Message Boards;Long-form articles;Videos;Lists of recommendations (tools, frameworks, technologies, etc.);Direct messaging of users;Chat (bot/AI)",7.0,NaN,10.0,1.0,6.0,5.0,4.0,2.0,11.0,15.0,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Writing code;Documenting code,NaN,Project planning;Debugging or fixing code;Deployment and monitoring;Predictive analytics,Learning about a codebase;Testing code;Committing and reviewing code;Generating content or synthetic data;Creating or maintaining documentation,Search for answers;Learning new concepts or technologies,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming;I’ve become less confident in my own problem-solving;Other (write in):",Yes,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have concerns about the security and privacy of data when using AI agents.,I am concerned about the accuracy of the information provided by AI agents.;It takes significant time and effort to learn how to use AI agents effectively.,The cost of using certain AI agent platforms is a barrier.,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I want to compare different solutions;When I’m stuck and can’t explain the problem;Other (please specify):,"Innovation, system design",72000.0,6.0
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.);Volunteering (regularly)",9.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps;Blogs or podcasts","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies","Technical documentation (is generated for/by the tool or system);Videos (not associated with specific online course or certification);Other online resources (e.g. standard search, forum, online community);Blogs or podcasts",15.0,Data engineer,"5,000 to 9,999 employees",Individual contributor,Remote,"Yes, I influenced the purchase of a tool that more than five colleagues use but it is not a substantial addition to the tech stack",Personal Project,5.0,7.0,13.0,4.0,9.0,8.0,12.0,2.0,11.0,14.0,NaN,11.0,13.0,10.0,1.0,5.0,9.0,7.0,8.0,2.0,15.0,NaN,Banking/Financial Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have transitioned into a new career and/or industry voluntarily,NaN,NaN,Ukraine,USD United States dollar,70000.0,NaN,Java;Python;Scala,Scala,Scala,NaN,NaN,NaN,Cassandra;Databricks SQL;DuckDB;Dynamodb;MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;Snowflake;Amazon Redshift,Dynamodb;MySQL;PostgreSQL,Dynamodb;MySQL;PostgreSQL,NaN,NaN,NaN,Amazon Web Services (AWS);Datadog;Docker;Microsoft Azure;Splunk,Amazon Web Services (AWS);Datadog;Microsoft Azure,Amazon Web Services (AWS);Datadog;Microsoft Azure,NaN,NaN,NaN,FastAPI;Spring Boot,NaN,NaN,NaN,NaN,NaN,IntelliJ IDEA;Notepad++;PyCharm;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Neither good or bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Data and analytics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);Engaged in paid work (10-19 hours per week),5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all media types);AI CodeGen tools or AI-enabled apps;Colleague or on-the-job training;Blogs or podcasts;Coding Bootcamp,"No, I learned something that was not related to AI or AI enablement as required for my job or to benefit my career",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source and is currently used by more than just myself but no purchase was made",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career and/or the industry I work in,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir;Erlang;F#;Fortran;GDScript;Go;Groovy;HTML/CSS;Java;JavaScript;Kotlin;Lisp;Lua;MATLAB;MicroPython;OCaml;Perl;PHP;PowerShell;Prolog;Python;R;Ruby;Rust;Scala;SQL;Swift;TypeScript;VBA;Visual Basic (.Net);Zig;Mojo,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scala;SQL;Gleam,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;InfluxDB;Microsoft SQL Server;MongoDB;Neo4J;Oracle;PostgreSQL;Snowflake;SQLite;Clickhouse;Cockroachdb;Pocketbase;Valkey,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;Datadog;Digital Ocean;Docker;Kubernetes;Netlify;New Relic;Ninja;npm;NuGet;Pip;pnpm;Podman;Poetry;Prometheus;Railway;Splunk;Supabase;Terraform;Vercel;Vite;Webpack;Yandex Cloud;Yarn,Ansible;Cargo;Cloudflare;Composer;Firebase;Google Cloud;Gradle;Heroku;Homebrew;IBM Cloud;Make;Maven (build tool);Microsoft Azure;MSBuild;Pacman;Pip,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;Blazor;Deno;Django;Drupal;Express;FastAPI;jQuery;React;Ruby on Rails;Spring Boot;Svelte;Symfony;Vue.js;WordPress;Axum,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;Phoenix;React,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google Gemini,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux (non-WSL),Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux (non-WSL),Airtable;Asana;Azure Devops;Clickup;Coda;Confluence;Doxygen;GitHub;GitLab;Google Colab;Google Workspace;Jira;Linear;Lucid (includes Lucidchart);Markdown File;Microsoft Planner;Miro;Monday.com;Notion;Obsidian;Redmine;Stack Overflow for Teams;Trello;Wikis;YouTrack,Notion;Obsidian,Notion;Obsidian,4,5,"Stack Overflow;Stack Exchange;Discord;Reddit;Dev.to;Hacker News;Hashnode;GitHub (public projects, not private repos);Slack (public channels, not work);Bluesky;X;Kaggle;YouTube;Twitch;LinkedIn;Substack;Medium;Company-sponsored forums",NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;openAI GPT (chatbot models),NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,"Message Boards;Videos;Coding challenges;Logic games/puzzles;Lists of recommendations (tools, frameworks, technologies, etc.);Job board;Day-in-the-life profiles/interviews with experts",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Writing code;Debugging or fixing code;Testing code;Committing and reviewing code;Deployment and monitoring;Predictive analytics;Generating content or synthetic data;Creating or maintaining documentation;Learning new concepts or technologies;Other (write in):,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming;I don’t use AI tools regularly;I’ve become less confident in my own problem-solving;It’s hard to understand how or why the code works;I haven’t encountered any problems",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automation;Decision intelligence;Data and analytics;Customer service support;Marketing,Language processing;Agent/multi-agent orchestration;Vector databases for AI applications;MCP servers,NaN,NaN,NaN,AI agents have increased my productivity.;AI agents have helped me automate repetitive tasks.;AI agents have improved the quality of my code.;AI agents have accelerated my learning about new technologies or codebases.;AI agents have helped me solve complex problems more effectively.;AI agents have reduced the time spent on specific development tasks.;AI agents have improved collaboration within my team.;Write in the most significant benefit if not listed above.,NaN,NaN,NaN,I am concerned about the accuracy of the information provided by AI agents.;Integrating AI agents with my existing tools and workflows can be difficult.;It takes significant time and effort to learn how to use AI agents effectively.,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security and privacy of data when using AI agents.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms;Write in the most significant challenge if not listed above:,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM watsonx.ai;Llama Index;Ollama;Semantic Kernel,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Enterprise Agents);OpenHands (formerly OpenDevin);Roo code (Roo-Cline);Tabnine,NaN,When I don’t trust AI’s answers;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,5,NaN,7.0

Виведемо кількість пропущених значень в стовпці ConvertedCompYearly:

In [22]:
print(f'NaN: {df_python['ConvertedCompYearly'].isna().sum()}')

NaN: 5701

Фільтруємо пусті значення:

In [23]:
#створюємо копію датафрейму і фільтруємо пусті значення
df_python_copy = df_python.copy()
df_python_copy = df_python[df_python['ConvertedCompYearly'].notna()]

Перевіряємо, чи правильно виконане фільтрування:

In [24]:
print(f'NaN: {df_python_copy['ConvertedCompYearly'].isna().sum()}')

NaN: 0

Виводимо середні та медіанні значення річної компенсації в розрізі країн:

In [25]:
#відображення усіх рядків датафрейму
#pd.set_option('display.max_rows', None)
converted_comp_by_year = df_python_copy.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median']).round().reset_index()
converted_comp_by_year

                                  Country      mean    median
0                             Afghanistan   22329.0    1000.0
1                                 Albania   47218.0   50000.0
2                                 Algeria   20187.0    7088.0
3                                 Andorra  226104.0  226104.0
4                     Antigua and Barbuda       1.0       1.0
..                                    ...       ...       ...
148  Venezuela, Bolivarian Republic of...    9909.0    3000.0
149                              Viet Nam  218837.0    8254.0
150                                 Yemen   32930.0   23672.0
151                                Zambia    5424.0    3206.0
152                              Zimbabwe   34000.0   25500.0

[153 rows x 3 columns]

<strong>Завдання 8.</strong> Аналіз освіти найбільш оплачуваних спеціалістів

Створюємо датафрейм converted_comp, фільтруємо пусті значення. Перевіряємо, чи фільтрація виконана правильно.

In [26]:
converted_comp = df[['ResponseId', 'ConvertedCompYearly', 'EdLevel']].dropna().reset_index(drop = True)
converted_comp.isna().sum()

ResponseId             0
ConvertedCompYearly    0
EdLevel                0
dtype: int64

In [27]:
converted_comp.head(5)

,ResponseId,ConvertedCompYearly,EdLevel
0,1,61256.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
1,2,104413.0,"Associate degree (A.A., A.S., etc.)"
2,3,53061.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
3,4,36197.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
4,5,60000.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"

Сортуємо датафрейм за компенсацією у спадному порядку, обираємо дані перших 5 респондентів.

In [28]:
converted_comp = converted_comp.sort_values(by = 'ConvertedCompYearly', ascending = False).reset_index(drop = True)
converted_comp.head(5)

,ResponseId,ConvertedCompYearly,EdLevel
0,34268,50000000.0,"Associate degree (A.A., A.S., etc.)"
1,28701,33552715.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
2,43144,18387548.0,"Associate degree (A.A., A.S., etc.)"
3,35354,15430267.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
4,45972,13921760.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"

<strong>Завдання 9.</strong> Аналіз популярності Python по віковим категоріям

В датафреймі python_stat створюємо стовпець WorkedWithPython, який містить значення True/False:

In [29]:
python_stat = df[['ResponseId', 'Age', 'LanguageHaveWorkedWith']].dropna()
python_stat = python_stat.copy()
python_stat['WorkedWithPython'] = df['LanguageHaveWorkedWith'].str.contains('Python', case = False, na = False)
python_stat.head(5)

,ResponseId,Age,LanguageHaveWorkedWith,WorkedWithPython
0,1,25-34 years old,Bash/Shell (all shells);Dart;SQL,False
1,2,25-34 years old,Java,False
2,3,35-44 years old,Dart;HTML/CSS;JavaScript;TypeScript,False
3,4,35-44 years old,Java;Kotlin;SQL,False
4,5,35-44 years old,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;PowerShell;Python;SQL;TypeScript;VBA;Visual Basic (.Net),True

Перевіряємо, чи правильно виконано фільтрацію

In [30]:
python_stat.isna().sum()

ResponseId                0
Age                       0
LanguageHaveWorkedWith    0
WorkedWithPython          0
dtype: int64

Створюємо датафрейм python_by_age, який містить інформацію про кількість респондентів, що програмують на Python, сумарну кількість респондентів та процентне співвідношення у розрізі вікових категорій:

In [31]:
python_by_age = python_stat.groupby('Age').agg(WorkedWithPython = ('WorkedWithPython', 'sum'), Total = ('ResponseId', 'count')).reset_index()
python_by_age['PythonPercentage'] = round((python_by_age['WorkedWithPython'] / python_by_age['Total']) * 100)
python_by_age

                 Age  WorkedWithPython  Total  PythonPercentage
0    18-24 years old              3684   5126              72.0
1    25-34 years old              6102  10257              59.0
2    35-44 years old              4862   8965              54.0
3    45-54 years old              2424   4483              54.0
4    55-64 years old               978   1986              49.0
5  65 years or older               298    678              44.0
6  Prefer not to say               118    176              67.0

Відображаємо лише необхідні стовпці:

In [32]:
python_by_age[['Age', 'PythonPercentage']]

                 Age  PythonPercentage
0    18-24 years old              72.0
1    25-34 years old              59.0
2    35-44 years old              54.0
3    45-54 years old              54.0
4    55-64 years old              49.0
5  65 years or older              44.0
6  Prefer not to say              67.0

<strong>Завдання 10.</strong> Аналіз індустрій серед високооплачуваних віддалених працівників

Створюємо маску для фільтрації респондентів, що працюють віддалено:

In [33]:
remote_mask = df['RemoteWork'] == 'Remote'
remote_mask

0         True
1        False
2        False
3         True
4        False
         ...
49186    False
49187    False
49188    False
49189    False
49190    False
Name: RemoteWork, Length: 49191, dtype: bool

Фільтруємо респондентів та обираємо необхідні стовпці:

In [48]:
remote_workers_stat = df.loc[remote_mask, ['ResponseId', 'ConvertedCompYearly', 'Industry']].dropna().reset_index(drop = True).sort_values(by = 'ConvertedCompYearly',ascending = False)
remote_workers_stat

,ResponseId,ConvertedCompYearly,Industry
4534,28701,33552715.0,Software Development
1750,10026,9000000.0,Government
4825,30729,6371285.0,Fintech
6058,40419,6000000.0,"Internet, Telecomm or Information Services"
4420,28059,3900000.0,"Internet, Telecomm or Information Services"
...,...,...,...
4988,32346,1.0,Software Development
5218,34866,1.0,Software Development
1651,9013,1.0,Manufacturing
6975,47177,1.0,Software Development
3447,20027,1.0,Software Development

Знаходимо значення Q3 для річної компенсації (ConvertedCompYearly):

In [51]:
remote_workers_quant_75 = remote_workers_stat['ConvertedCompYearly'].quantile(0.75)
remote_workers_quant_75

np.float64(150000.0)

Фільтруємо рядки зі значенням ConvertedCompYearly більше за Q3:

In [55]:
remote_workers_perc_75 = remote_workers_stat[remote_workers_stat['ConvertedCompYearly'] > remote_workers_quant_75].reset_index(drop = True)
remote_workers_perc_75

,ResponseId,ConvertedCompYearly,Industry
0,28701,33552715.0,Software Development
1,10026,9000000.0,Government
2,30729,6371285.0,Fintech
3,40419,6000000.0,"Internet, Telecomm or Information Services"
4,28059,3900000.0,"Internet, Telecomm or Information Services"
...,...,...,...
1681,34098,150588.0,Media & Advertising Services
1682,2184,150588.0,Software Development
1683,37668,150588.0,Software Development
1684,16040,150300.0,Other:
1685,15063,150294.0,Healthcare

Рахуємо кількість респондентів в розрізі індустрій та сортуємо в порядку спадання:

In [65]:
remote_75_by_industry = remote_workers_perc_75.groupby('Industry').agg(RespondentsCount = ('ResponseId', 'count')).sort_values(by = 'RespondentsCount', ascending = False)
remote_75_by_industry

                                            RespondentsCount
Industry
Software Development                                     829
Fintech                                                  137
Healthcare                                               120
Other:                                                   117
Internet, Telecomm or Information Services                94
Banking/Financial Services                                58
Media & Advertising Services                              54
Retail and Consumer Services                              48
Government                                                47
Computer Systems Design and Services                      43
Transportation, or Supply Chain                           43
Insurance                                                 28
Energy                                                    27
Manufacturing                                             25
Higher Education                                          16